"""
Core Pydantic schemas for HarnessCore agent state.
"""
import operator
from typing import Annotated, Literal, Optional, Any
from pydantic import BaseModel, Field


class TokenUsage(BaseModel):
    """Tracking token consumption for an LLM call."""
    input_tokens: int = 0
    output_tokens: int = 0
    thinking_tokens: int = 0


class TaskLog(BaseModel):
    """A single log entry from an agent action."""

    agent_name: str
    action_type: str
    input_context: Optional[str] = Field(None, description="Detailed request or context provided to the agent")
    details: str = Field(..., description="High-level action summary")
    logs: Optional[str] = Field(None, description="Detailed execution logs (tool outputs, errors, etc.)")
    status: Literal["SUCCESS", "FAIL", "IN_PROGRESS"]
    tokens: TokenUsage = Field(default_factory=TokenUsage)


class SystemState(BaseModel):
    """The shared state object passed between all LangGraph nodes."""

    messages: Annotated[list[dict], operator.add] = Field(
        default_factory=list,
        description="Full conversation history (messages)",
    )
    user_prompt: str = Field(description="The latest user requirement or message")
    current_assignee: str = Field(default="PO", description="Agent currently holding control")

    tasks: dict[str, str] = Field(
        default_factory=dict,
        description="Task list generated by PO (TaskID: Description)",
    )
    completed_tasks: list[str] = Field(default_factory=list)
    file_changes: list[str] = Field(
        default_factory=list, description="File paths modified in the current branch"
    )
    history_logs: Annotated[list[TaskLog], operator.add] = Field(
        default_factory=list,
        description="Full execution log of all agent actions",
    )
    total_tokens: TokenUsage = Field(
        default_factory=TokenUsage,
        description="Accumulated token usage across the entire project"
    )
    latest_error: Optional[str] = Field(
        default=None, description="Latest error message from QA Evaluator"
    )
    next_agent: Optional[str] = Field(
        default=None,
        description="Routing signal: next agent node name or 'FINISH'",
    )

    @classmethod
    def model_validate(cls, obj: Any, *args, **kwargs) -> "SystemState":
        """Ensure nested fields are coerced correctly from dicts."""
        if isinstance(obj, dict):
            # Coerce history_logs
            if "history_logs" in obj and isinstance(obj["history_logs"], list):
                obj["history_logs"] = [
                    msg if isinstance(msg, TaskLog) else TaskLog.model_validate(msg)
                    for msg in obj["history_logs"]
                ]
            # Coerce total_tokens
            if "total_tokens" in obj and isinstance(obj["total_tokens"], dict):
                obj["total_tokens"] = TokenUsage.model_validate(obj["total_tokens"])
        return super().model_validate(obj, *args, **kwargs)

# Order of rebuild matters: children first
TokenUsage.model_rebuild()
TaskLog.model_rebuild()
SystemState.model_rebuild()
