"""
Core Pydantic schemas for HarnessCore agent state.
"""
from __future__ import annotations

from typing import Annotated, Literal, Optional
import operator
from pydantic import BaseModel, Field


class TaskLog(BaseModel):
    """A single log entry from an agent action."""

    agent_name: str
    action_type: str
    details: str
    status: Literal["SUCCESS", "FAIL", "IN_PROGRESS"]


class SystemState(BaseModel):
    """The shared state object passed between all LangGraph nodes."""

    user_prompt: str = Field(description="The original user requirement")
    current_assignee: str = Field(default="PO", description="Agent currently holding control")
    tasks: dict[str, str] = Field(
        default_factory=dict,
        description="Task list generated by PO (TaskID: Description)",
    )
    completed_tasks: list[str] = Field(default_factory=list)
    file_changes: list[str] = Field(
        default_factory=list, description="File paths modified in the current branch"
    )
    history_logs: Annotated[list[TaskLog], operator.add] = Field(
        default_factory=list,
        description="Full execution log of all agent actions",
    )
    latest_error: Optional[str] = Field(
        default=None, description="Latest error message from QA Evaluator"
    )
    next_agent: Optional[str] = Field(
        default=None,
        description="Routing signal: next agent node name or 'FINISH'",
    )
